feat: add grpc-web support #102
crossplane-contrib/provider-argocd pull request #103
Opened 2023-10-16 11:05 UTC by Avarei

### Description of your changes

Implements #102

Adds optional fields `GRPCWeb` and `GRPCWebRootPath` to providerconfig and hands them over to the argocd client library.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Created a cluster object in an argocd behind a proxy without gRPC support.
Created another cluster object in an argocd within the same cluster over a k8s service (grpcWeb set to false).

I was not yet able to test GRPCWebRootPath

[contribution process]: https://git.io/fj2m9

2023-10-25 14:07 UTC, MisterMX requested changes

2023-10-25 14:07 UTC, MisterMX commented on apis/v1alpha1/providerconfig_types.go
> +	GRPCWebRootPath string `json:"grpcWebRootPath,omitempty"`
Optional fields should be a pointer

```suggestion
	GRPCWebRootPath *string `json:"grpcWebRootPath,omitempty"`
```

2023-10-25 14:07 UTC, MisterMX commented on pkg/clients/argocd.go
> +	}
Can be simplied with https://pkg.go.dev/k8s.io/utils@v0.0.0-20230726121419-3b25d923346b/ptr#Deref

```suggestion
	grpcWeb := ptr.Deref(pc.Spec.GRPCWeb, false)
```

2023-10-25 21:49 UTC, Avarei commented
I implemented your feedback and successfully ran `make reviewable` again.
I did not test these changes against an argocd yet. I will do that on monday.

2023-10-30 14:08 UTC, Avarei commented
For me everything is working as expected in my cluster and agains my argocd

2023-11-02 16:16 UTC, MisterMX approved these changes
LGTM. Thank you very much @Avarei!

2023-11-02 16:16 UTC, merged