Cluster managed resource
crossplane-contrib/provider-argocd pull request #12
Opened 2021-11-24 16:08 UTC by Benedikt1992

### Description of your changes

Fixes #7

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

Tests are in progress

### How has this code been tested
Manually with the following configurations:

```yaml
---
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    server: https://kubernetes.default.svc
    name: example-cluster
    config:
      tlsClientConfig:
        insecure: true
  providerConfigRef:
    name: argocd-provider
```

```yaml
---
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    server: https://kubernetes.default.svc
    name: example-cluster
    config:
      bearerTokenRef:
        name: secret-bearer
        namespace: default
        key: password
      tlsClientConfig:
        insecure: true
  providerConfigRef:
    name: argocd-provider
```

[contribution process]: https://git.io/fj2m9

2021-11-24 16:23 UTC, Benedikt1992 commented on apis/cluster/v1alpha1/types.go
> +	RefreshRequestedAt *metav1.Time `json:"refreshRequestedAt,omitempty"`
I feel like wee don't need this field in the managed resource. What do you think?

2021-11-24 16:34 UTC, Benedikt1992 commented on apis/cluster/v1alpha1/types.go
> +	KeyData []byte `json:"keyData,omitempty"`
To me it seems that they just used the default `TLSClientConfig` struct ([TLSClientConfig](https://pkg.go.dev/github.com/argoproj/argo-cd/v2@v2.0.1/pkg/apis/application/v1alpha1#TLSClientConfig))

It doesn't really make sense to have a Key field. Should we remove the field?

2021-11-30 12:39 UTC, janwillies requested changes
thanks a lot @Benedikt1992! Some small comments already in a first review

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	RefreshRequestedAt *metav1.Time `json:"refreshRequestedAt,omitempty"`
that is correct, please remove

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	PasswordRef *SecretReference `json:"passwordRef,omitempty"`
```suggestion
	PasswordSecretRef *SecretReference `json:"passwordSecretRef,omitempty"`
```
The pattern for other providers has been to add `xxxSecretRef` if it's a reference to a Kubernetes Secret, see for example: https://doc.crds.dev/github.com/crossplane/provider-aws/secretsmanager.aws.crossplane.io/Secret/v1alpha1@v0.21.1#spec-forProvider-stringSecretRef

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	Password *string `json:"password,omitempty"`
I believe this field should be removed, as we don't want passwords to end up in plain text

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	BearerToken *string `json:"bearerToken,omitempty"`
same as above, please remove

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	BearerTokenRef *SecretReference `json:"bearerTokenRef,omitempty"`
```suggestion
	BearerTokenSecretRef *SecretReference `json:"bearerTokenSecretRef,omitempty"`
```

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	Env *map[string]string `json:"env,omitempty"`
do we need a pointer to the `map` here? If not, I suggest removing it

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	CertDataRef *SecretReference `json:"certDataRef,omitempty"`
```suggestion
	CertDataSecretRef *SecretReference `json:"certDataSecretRef,omitempty"`
```

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	CADataRef *SecretReference `json:"caDataRef,omitempty"`
```suggestion
	CADataSecretRef *SecretReference `json:"caDataSecretRef,omitempty"`
```

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	CAData []byte `json:"caData,omitempty"`
This can probably remain, see the ongoing discussion here: https://github.com/crossplane/provider-aws/issues/955#issuecomment-974599207

2021-11-30 12:39 UTC, janwillies commented on apis/cluster/v1alpha1/types.go
> +	CertData []byte `json:"certData,omitempty"`
please remove

2021-12-01 17:37 UTC, Benedikt1992 commented on apis/cluster/v1alpha1/types.go
> +	KeyData []byte `json:"keyData,omitempty"`
We copy the argocd api

2021-12-01 17:40 UTC, Benedikt1992 commented on apis/cluster/v1alpha1/types.go
> +	PasswordRef *SecretReference `json:"passwordRef,omitempty"`
Done. This applies to Repositories as well. Will fix this in another PR

2021-12-01 17:41 UTC, Benedikt1992 commented on apis/cluster/v1alpha1/types.go
> +	Password *string `json:"password,omitempty"`
Indeed it will end up in plaintext. removed original fields

2021-12-08 14:41 UTC, janwillies approved these changes
Thanks a lot @Benedikt1992! This is crucial for adding Kubernetes cluster to ArgoCD in a secure way via crossplane 👍

2021-12-08 14:41 UTC, merged