chore: updates from crossplane-provider-template
crossplane-contrib/provider-argocd pull request #121
Opened 2023-12-21 09:24 UTC by maximilianbraun

### Description of your changes

I noticed that the provider-template emerged a bit away from the argocd-providers structure, let it be `internal` instead of `pkg` for the place for controllers etc, or some updates to the make file which help to create new types. As well as some updates to the Github workflows. 

This is an attempt to make it simpler for new contributors to feel home, like with other crossplane providers.

Let me know what you think ✌️

What I did not adjust from provider template:
* Pushing the provider image.
* stale workflow
* updates to integration_test.sh
* dependencies updates (like c-runtime)
* provider.prepare (make) target, which us responsible to rename the template provider to smth meaningful

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- Tests ran successful
- docker image build successfully

[contribution process]: https://git.io/fj2m9

2023-12-21 13:26 UTC, janwillies commented
Thank you so much for this! Indeed this provider was created quite a while ago, and new practises have emerged since then. I'm going to take a look at this

2023-12-21 15:47 UTC, MisterMX requested changes

2023-12-21 15:47 UTC, MisterMX commented on internal/clients/applications/client.go
I am generally not very happy with the approach of putting all logic into `internal` instead of `pkg`. Per Go convention it is not allowed to import `internal` packages in other modules which would prevent others from reusing the logic of this controller. (I don't have a use case at hand but I don't want to discourage code sharing just because its in the template since there is no technical reason for it to be that way. Its actually a pain to reuse Crossplane's internal logic in other projects because they do exactly that.) So I would not vote for not making this change.

The other changes are OK, though.

2023-12-21 16:07 UTC, maximilianbraun commented on internal/clients/applications/client.go
I don't have a strong opinion; PR updated.

2023-12-22 14:46 UTC, MisterMX approved these changes
LGTM. Thank you very much @maximilianbraun for this very nice Christman present! Happy holidays!

2023-12-22 14:46 UTC, merged