feat: Add Repository secret observation
crossplane-contrib/provider-argocd pull request #156
Opened 2024-03-29 09:36 UTC by oskisk

### Description of your changes 

Trigger a resource update on secret changes for all the references within the repository controller.

Fixes #36

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- Added basic unit tests for the repository controllers
- Manual test for referenes and observations

[contribution process]: https://git.io/fj2m9

2024-04-04 09:18 UTC, oskisk commented
@MisterMX Would you have time to review this PR?

2024-04-08 13:02 UTC, MisterMX requested changes
Thanks for this PR @oskisk! I made some minor remarks. Can you take a look at them?

2024-04-08 13:02 UTC, MisterMX commented on pkg/controller/repositories/controller.go
> +			}, nil
This can be simplified into 
```suggestion
		return managed.ExternalObservation{}, resource.Ignore(err, repositories.IsErrorRepositoryNotFound)
```

2024-04-08 13:02 UTC, MisterMX commented on pkg/controller/repositories/controller.go
> +	observerdRepository, err := e.client.Get(ctx, &repoQuery)
Typo 
```suggestion
	observedRepository, err := e.client.Get(ctx, &repoQuery)
```

2024-04-09 08:37 UTC, oskisk commented on pkg/controller/repositories/controller.go
> +	observerdRepository, err := e.client.Get(ctx, &repoQuery)
Fixed the typo, thx.

2024-04-09 08:37 UTC, oskisk commented on pkg/controller/repositories/controller.go
> +			}, nil
Thank you, I have changed it to your suggestion.

2024-04-09 08:39 UTC, oskisk commented
> Thanks for this PR @oskisk! I made some minor remarks. Can you take a look at them?

Thank you for reviewing. I've made the changes to the branch based on your suggestions.

2024-04-23 16:12 UTC, MisterMX approved these changes
LGTM. Thank you very much @oskisk!

2024-04-23 16:12 UTC, merged