feat: add Argo CD Application
crossplane-contrib/provider-argocd pull request #67
Opened 2023-06-02 14:30 UTC by maximilianbraun

### Description of your changes

* added support for Argo CD Applications
* added conversion of structs via `goverter` (used within Crossplane as well)
* added `mockgen` to be executed with `go generate ./...`
* added 2 make targets for simpler local dev + little shell script
* updated k8s clients, i had some issues with building
* updated `golangci-lint` version, which contained a contained a couple fixes regarding resource usage

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Unit tests have been added to the controllers & manual integration tests. 

[contribution process]: https://git.io/fj2m9

2023-06-02 15:26 UTC, janwillies commented
Thanks a lot @maximilianbraun for this massive contribution! We'll take a look soon

2023-06-06 13:10 UTC, MisterMX requested changes

2023-06-06 13:10 UTC, MisterMX commented on examples/projects/project.yaml
> -    name: argocd-provider
There should always be a LF at the end of a file.

2023-06-06 13:10 UTC, MisterMX commented on go.mod
> +replace k8s.io/sample-controller => k8s.io/sample-controller v0.26.3
Please rebase on the latest `main` and keep all the `replace`s in a single block.

2023-06-06 13:10 UTC, MisterMX commented on apis/applications/v1alpha1/status.go
> +	Revision string `json:"revision,omitempty" protobuf:"bytes,2,opt,name=revision"`
Optional fields should be pointer types. But I don't know whether this will work with goverter...

2023-06-06 13:10 UTC, MisterMX commented on Makefile
> +GOLANGCILINT_VERSION ?= 1.53.1
As long as there is no necessity please stick to the currently specified version.

2023-06-06 13:10 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +			Name: name,
`Name` should always be `meta.GetExternalName(cr)`.

If the external name is not set but needed, the external name should be set by an initializer, like so: https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/docdb/dbcluster/setup.go#L76

2023-06-06 13:10 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +	return reflect.DeepEqual(*cluster, remote.Spec)
Best use `cmp.Equal` as it is also used elsewhere.

```suggestion
	return cmp.Equal(*cluster, remote.Spec)
```

2023-06-06 13:10 UTC, MisterMX commented on apis/applications/v1alpha1/types.go
> +	Namespace         string   `json:"namespace,omitempty" protobuf:"bytes,4,opt,name=namespace"`
Optional fields should be a pointer.

2023-06-06 15:07 UTC, maximilianbraun commented
> Thanks for your contribution @maximilianbraun! Can you take a lot a the remarks I have added?

Sure thing. Let me have a look :)

2023-06-06 15:19 UTC, maximilianbraun commented on Makefile
> +GOLANGCILINT_VERSION ?= 1.53.1
Oh yeah mate, I had a specific problem with memory consumption on my box which was fixed with raising the version. Let me see how the linter behaves after updating of the `build` tooling

2023-06-09 10:15 UTC, MisterMX requested changes
@maximilianbraun looking good already. I marked some last things that need to be fixed before merging.

2023-06-09 10:15 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +	createRequest := generateCreateApplicationRequest(&cr.Spec.ForProvider, cr.Name)
```suggestion
	createRequest := generateCreateApplicationRequest(cr)
```

2023-06-09 10:15 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +		}, nil
Can be simplified

```suggestion
		return managed.ExternalObservation{}, nil
```

2023-06-09 10:15 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +}
Make it simpler by passing `cr` and get the name automatically.

```suggestion
func generateCreateApplicationRequest(p *v1alpha1.Application) *application.ApplicationCreateRequest {
	converter := v1alpha1.ConverterImpl{}
	spec := converter.ToArgoApplicationSpec(&p.Spec.ForProvider)

	app := &argocdv1alpha1.Application{
		TypeMeta: metav1.TypeMeta{},
		ObjectMeta: metav1.ObjectMeta{
			Name: meta.GetExternalName(cr),
		},
		Spec: *spec,
	}

	repoCreateRequest := &application.ApplicationCreateRequest{
		Application: app,
	}

	return repoCreateRequest
}
```

2023-06-09 10:15 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +}
Make it simpler by passing `cr` and get the name automatically:

```suggestion
func generateUpdateRepositoryOptions(cr *v1alpha1.Application) *application.ApplicationUpdateRequest {
	converter := v1alpha1.ConverterImpl{}

	spec := converter.ToArgoApplicationSpec(&cr.Spec.ForProvider)

	app := &argocdv1alpha1.Application{
		TypeMeta: metav1.TypeMeta{},
		ObjectMeta: metav1.ObjectMeta{
			Name: meta.GetExternalName(cr),
		},
		Spec: *spec,
	}

	o := &application.ApplicationUpdateRequest{
		Application: app,
	}
	return o
}
```

2023-06-09 10:15 UTC, MisterMX commented on pkg/controller/applications/controller.go
> +	updateRequest := generateUpdateRepositoryOptions(&cr.Spec.ForProvider, name)
```suggestion
	updateRequest := generateUpdateRepositoryOptions(cr)
```

2023-06-09 13:10 UTC, MisterMX approved these changes
LGTM. Thanks a lot @maximilianbraun!

2023-06-09 13:11 UTC, merged